Parameters:
  EnvId:
    Type: String
    Default: "devel"
  CertificateArn:
    Type: String
    Default: "arn:aws:acm:us-east-1:932529686876:certificate/ff26c860-8432-4ecf-ba49-0d574e3b591c"
    Description: "ARN of the ACM certificate to use for HTTPS"

Resources:
  CfnCloudFrontDistribution:
      Type: 'AWS::CloudFront::Distribution'
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: 
                Fn::ImportValue:
                  !Sub "${EnvId}-APIEndpoint"
              Id: APIOrigin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          Enabled: true
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: APIOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
          ViewerCertificate:
            AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
