# sam deploy --stack-name "$ENV_ID-db" --template-file infra_db.cfn.yaml --resolve-s3 --capabilities CAPABILITY_IAM --parameter-overrides EnvId="$ENV_ID"

AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template: MariaDB Database'
Parameters:
  EnvId:
    Type: String
    Default: "devel" 
  AllowCIDR:
    Description: The CIDR block for the security group
    Type: String
    Default: '0.0.0.0/0'
  AllocatedStorage:
    Description: AllocatedStorage
    Type: Number
    Default: 5
  DBClusterInstanceClass:
    Description: InstanceClass
    Type: String
    Default: 'db.t3.micro'
  PubliclyAccessible:
    Description: PubliclyAccessible
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
  DBName:
    Type: String
    Default: "s3quarkus"
  DBUsername:
    Type: String
  DBPassword:
    Type: String

Resources:
  CfnDbSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for MariaDB Database'
      VpcId: 
        Fn::ImportValue:
          !Sub '${EnvId}-VPCId'

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref AllowCIDR

  CfnDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'Subnet group for DB'
      SubnetIds: 
        - Fn::ImportValue:
            !Sub '${EnvId}-PublicSubnet1Id'
        - Fn::ImportValue:
            !Sub '${EnvId}-PublicSubnet2Id'

  CfnDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: 'mariadb'
      EngineVersion: '10.11'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups: 
        - !GetAtt  CfnDbSecurityGroup.GroupId
      DBSubnetGroupName: !Ref CfnDBSubnetGroup
      PubliclyAccessible: !Ref PubliclyAccessible
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: !Ref DBClusterInstanceClass
      DBName: !Ref DBName

Outputs:
  DBInstanceIdentifier:
    Description: The identifier of the DB instance
    Value: !Ref CfnDBInstance
  DBInstanceEndpoint:
    Description: The connection endpoint for the DB instance
    Value: !GetAtt CfnDBInstance.Endpoint.Address
  DBInstancePort:
    Description: The port number on which the DB instance accepts connections
    Value: !GetAtt CfnDBInstance.Endpoint.Port
  DBInstanceSecurityGroup:
    Description: The security group of the DB instance
    Value: !GetAtt CfnDbSecurityGroup.GroupId
  JDBCURL:
    Description: JDBC URL
    Value: !Sub "jdbc:mariadb://${CfnDBInstance.Endpoint.Address}:${CfnDBInstance.Endpoint.Port}/${DBName}"
    Export:
      Name:  !Sub "${EnvId}-JDBCURL"

